Feature/network connect
DailyPoem/DailyPoem-Client pull request #9
Opened 2022-07-04 01:37 UTC by ckrudals

## 변경사항

- base url 변경
- response data 변경
- Klint 적용

2022-07-04 11:28 UTC, patrick0422 requested changes

2022-07-04 11:28 UTC, patrick0422 commented on app/src/main/java/com/patrick/dailypoem/data/model/PoemData.kt
> +    val `data`: Data?,
변수명 수정 부탁드립니다

2022-07-04 11:28 UTC, patrick0422 commented on app/build.gradle.kts
> +    implementation("com.jakewharton.timber:timber:4.7.1")
수정 요망

2022-07-04 11:28 UTC, patrick0422 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +        "com.kakao.sdk:v2-navi:2.4.2", // 카카오내비
안 쓰이는 건 삭제 부탁 드립니다.

2022-07-04 11:28 UTC, patrick0422 commented on app/src/main/java/com/patrick/dailypoem/ui/ShareBottomSheet.kt
> +}
기능 간소화로 안 쓰일 것 같은데 아쉽지만 삭제하는게 낫지 않을까요?

2022-07-04 11:28 UTC, patrick0422 commented on app/src/main/java/com/patrick/dailypoem/ui/MainActivity.kt
> +            .setAction("확인") {}
중복된 것 같은데 확인 부탁드립니다.

2022-07-04 11:28 UTC, patrick0422 commented on app/src/main/java/com/patrick/dailypoem/data/model/PoemData.kt
> +)
nullable이 아니어도 될 것 같은데용

2022-07-04 11:28 UTC, patrick0422 commented on app/src/main/java/com/patrick/dailypoem/data/model/Data.kt
> +    val epitagram: String?
nullable인 이유가 있나요?

2022-07-04 11:28 UTC, patrick0422 commented on app/src/main/java/com/patrick/dailypoem/ui/MainActivity.kt
> +                val message = poemResult.data?.data?.epitagram ?: notFoundMessage
PoemData 파라미터의 nullable 삭제되면 여기도 수정 부탁드립니다.

2022-07-05 05:00 UTC, ckrudals commented on app/src/main/java/com/patrick/dailypoem/ui/ShareBottomSheet.kt
> +}
저 bottomSheetDialog 자체가 안쓰입니다. 그래서 관련된건 삭제했으니 확인 부탁드립니다.

2022-07-05 05:20 UTC, patrick0422 approved these changes

2022-07-05 05:21 UTC, patrick0422 approved these changes

2022-07-05 05:23 UTC, merged